# Site settings
title: rdark
email: richard@fohnet.co.uk
description: >
  Personal site of Richard Clark
baseurl: ""
url: "https://rdark.github.io"
github_username:  rdark
exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
# Build settings
markdown: kramdown
krmdown:
  input: GFM
